# Generated with RailsBricks
# Initial seed file to use with Devise User Model

# Temporary admin account
# u = User.new(
#     username: "admin",
#     email: "admin@example.com",
#     password: "1234",
#     password_confirmation: "1234",
#     admin: true
# )
# u.skip_confirmation!
# u.save!



# # Test user accounts
# (1..50).each do |i|
#   u = User.new(
#       username: "user#{i}",
#       email: "user#{i}@example.com",
#       password: "1234",
#       password_confirmation: "1234"
#   )
#   u.skip_confirmation!
#   u.save!

#   puts "#{i} test users created..." if (i % 5 == 0)

# end
  
categorias = ["Aire libre", "Café", "Cine", "Comida", "Compras", "Deporte", "Entretenimiento", "Noche"]
categorias.each do |cat|
  a = Category.new(name: cat)
  a.save!
end



##SITIOS SEED
sitios = [
    ["La Hakima","Centro Hípico La Hakima",1,"","Camino Paraje Montaña el Púlpito, 83",38206,"660 846 891","samuel.lahakima@gmail.com","http://www.centrohipicolahakima.es/es/",28.4909859,-16.3578875,"Centro hípico con clases de equitación a todos los niveles, largos paseos a caballo y una multitud de actividades para niños o celebraciones","Un lugar ideal para disfrutar, no sólo los aficionados a la hípica, sino también todos aquellos a los que les guste disfrutar del aire libre y la naturaleza.","Monitores profesionales con experiencia en equitación, clases de equitación a todos los niveles para adultos y niños/as, paseos a caballo, picnic, excursiones, campamentos, acampadas, actividades para colegios, celebraciones, y un sin fin de divertidas actividades."],
    ["Kiraya","Kiraya Bikes",1,"","Avenida Milán, 71",38206,"686 702 929","info@kirayabikes.com","http://www.kirayabikes.com/",28.5398156,-16.3612211,"Ofrecemos a los visitantes de la isla de Tenerife un turismo activo, con rutas en bicicleta organizadas por nosotros, o simplemente el alquiler de la bicicleta, para que el cliente desarrolle su ruta por la isla, facilitándole la entrega a domicilio de la bici alquilada. Mostramos sitios interesantes de Tenerife que pocos turistas conocen, como son los montes del macizo de Anaga, la Esperanza, y muchos más, ¡todo ello en un medio de transporte limpio y saludable, la bicicleta!","Nuestra afición por las bicicletas viene desde nuestra infancia. Es a partir de ahí lo que nos ha llevado a la creación de Kiraya Bikes.","Diferentes rutas: Anaga-Tegueste, Izaña-La Caldera, Volcán Chinyero..."],
    ["Mesa Mota","Monte de la Mesa Mota",1,"","Calle de la Mesa Mota s/n",38206,"","","",28.5007814,-16.3156576,"Una excelente zona recreativa, que también es utilizada como mirador natural para observar la ciudad de La Laguna, un espacio apetecible para pasear entre los brezos y pinos que pueblan la mesa mota.","Lugar ideal para realizar actividades deportivas, chuletadas con los amigos o simplemente para ir a tomar un descanso.","Utilizado por uiversitarios para realizar grandes fiestas de hasta el millar de personas para celebrar chuletadas en honor a cada facultad."],
    ["Bajamar","Piscinas de Bajamar",1,"","Avenida del Sol, 33",38250,"","","",28.5537716,-16.3449282,"Piscinas naturales de mar. El conjunto está formado por dos piscinas grandes para adultos y una pequeña para niños, todas de agua de mar y dispone de duchas y vestuarios.","El ambiente es familiar y las piscinas están siempre muy concurridas. Por su céntrica situación, en el mismo casco urbano de la zona, hay cerca varios restaurantes y cafeterías.","El entorno está perfectamente habilitado para disfrutar de un paseo por la costa. Al lado de las piscinas, se ubica el faro de Bajamar y una pequeña playa de arena protegida por una escollera."],
    ["Época","Café Época",2,"","Calle Heraclio Sánchez, 5",38204,"922 26 31 53","","https://es-es.facebook.com/barcafeepoca",28.484873,-16.316370,"Café literario con tenue música de jazz con chocolates bebidos, comidos o con alcohol. Café bohemio, con buen trato al cliente, luz tenue y una decoración que lo hace intimo y familiar. Además tienen una gran variedad de libros (intercambiables si deseas llevar otro), juegos de mesa (ajedrez, jenga, damas), un piano y exposiciones temporales (pintura, fotografía).","Sin duda la característica de este local es su toque bohemio, parece que al entrar nos transportaran al pasado. Sin duda es un lugar de los difíciles de encontrar.","Es muy agradable y a veces hay personas tocando el piano. Siempre vale la pena pasarse a merendar, tomar un té con tarta con una amigo o jugar al parchís."],
    ["Palmelita","Café Palmelita",2,"","Plaza de la Concepción, 14",38201,"922 25 04 05","","http://www.palmelita.es/",28.497208,-16.320148,"Pastalerías y cafeterías Palmelita ofrece excelentes especialidades de pastelería, panadería y confitería europea","Diferentes establecimientos, como son en Bajamar, San Cristóbal de La Laguna y Santa Cruz de Tenerife.","Nuestras especialidades pueden ser disfrutadas en nuestras pastelerías-cafeterías y acompañadas por ejemplo, con un aromático café o té."],
    ["Melita","Café Melita",2,"","Carretera General de Bajamar, 171",38250,"922 54 08 14","","http://www.palmelita.es/",28.556348,-16.335961,"Pastalerías y cafeterías Palmelita ofrece excelentes especialidades de pastelería, panadería y confitería europea","Diferentes establecimientos, como son en Bajamar, San Cristóbal de La Laguna y Santa Cruz de Tenerife.","Nuestras especialidades pueden ser disfrutadas en nuestras pastelerías-cafeterías y acompañadas por ejemplo, con un aromático café o té."],
    ["Don Tito","Café Don Tito",2,"","Calle Herradores, 88",38201,"922 26 31 48","","",28.4893057,-16.3187639,"Agradable café donde tomar un buen vaso de chocolate caliente, sin dejar de probar sus ricas tartas caseras de calabaza.","Lugar perfecto para charlar con los amigos y descubrir nuevos aromas del café.","Cada jueves se organiza Language café en la planta superior para que la gente pueda aprender a nuevas idiomas, practicar y mejorar su competencia de lenguas o charlar. Todo gratis y muy divertido."],
    ["Exodus","Exodus: Dioses y Reyes",3,"","Camino de la Hornera s/n",38291,"922 82 10 61","","",28.463803,-16.305529,"Dirigida por el aclamado director de 'Gladiator', Ridley Scott, 'Exodus: Dioses y reyes' cuenta la vida del personaje bíblico de Moisés, donde, desafiante, se levanta en contra de su hermanastro el faraón egipcio Ramsés para liberar a los 600.000 esclavos que tiene a su merced. Para ello usará temibles plagas para luego embarcarse en un monumental viaje.","Christian Bale y Joel Edgerton co-protagonizan esta bíblica película co-escrita por los guionistas de 'Admitido' y 'GoldenEye'.","Ridley Scott revisa el relato bíblico de Moisés con una impresionante factura técnica pero con muchos problemas para mantener el ritmo en su larga duración."],
    ["Sinsajo Pt.1","Los Juegos del Hambre: Sinsajo Pt.1",3,"","Camino de la Hornera s/n",38291,"922 82 10 61","","",28.463803,-16.305529,"En el desenlace de la trilogía distópica, una malherida e incluso afectada mentalmente Katniss deberá adaptarse a su nueva vida después de que los rebeldes del 'desaparecido' Distrito 13 la rescaten de la Arena al final de la 75 edición de los Juegos.","¿Continuará la bella y astura protagonista saliendo victoriosa de sus enfrentamientos?","Esta película nos acerca a la última entrega de la saga, Sinsajo Parte 2, con la que concluirá la exitosa producción."],
    ["El Hobbit","El Hobbit: La batalla de los cinco ejércitos",3,"","Camino de la Hornera s/n",38291,"922 82 10 61","","",28.463803,-16.305529,"Después de haber recuperado el reino del Dragón Smaug en la montaña, la Compañía ha desencadenado, sin querer, una potencia maligna. Un Smaug enfurecido vuela hacia la Ciudad del Lago para acabar con cualquier resto de vida. Obsesionado con las enormes riquezas en su poder, el rey enano Thorin se vuelve codicioso, mientras Bilbo intenta hacerle entrar en razón haciendo algo desesperado y peligroso."," Pero hay aún mayores peligros por delante. Sin la ayuda del mago Gandalf, su gran enemigo Sauron ha enviado legiones de orcos hacia la Montaña Solitaria en un ataque épico.","El Hobbit: la Batalla de los Cinco Ejércitos, es la tercera parte de la adaptación cinematográfica de la novela de J. R. R. Tolkien El hobbit."],
    ["El Séptimo Hijo","El Séptimo Hijo",3,"","Camino de la Hornera s/n",38291,"922 82 10 61","","",28.463803,-16.305529,"Thomas Ward (Ben Barnes) tiene trece años, es el séptimo hijo de un séptimo hijo y vive feliz en una granja junto a sus padres, su hermano y su cuñada embarazada. Todo cambia cuando, una tarde, viene a buscarlo un Espectro para llevárselo como aprendiz. Junto a él deberá enfrentarse a criaturas malignas: brujas, boggarts, espíritus y aparecidos.","Thomas no quiere marcharse pero su madre, que tiene poderes ocultos, insiste en que ésa es su obligación y su misión en el mundo. Así pues, no tiene más remedio que obedecer. Adaptación del libro homónimo de Joseph Delaney.","Ha tardado lo suyo, pero ya está aquí la adaptación cinematográfica de 'The Spook's Apprentice' obra del escritor Joseph Delaney. 'El séptimo hijo', en cines a partir del próximo 1 de enero."],
    ["El Aljibe","Tasca el Aljibe",4,"","Camino Tabares, 18",38330,"922 63 61 11","","http://tascaelaljibe.es/",28.491745,-16.371916,"Restaurante de cocina contemporánea amplio y separado en varias salas, sitio agradable donde disfrutar de una buena comida. Ofrece una relación calidad precio de muy buen nivel. Algunas de las personas que han visitado este lugar recomiendan algunas de sus especialidades como pueden ser las batatas con bavalao, el solomillo a las tres salsas o las garbanzas. También posee una buena variedad de ensaladas entre las que encontramos la ensalada de bacalao con frutos secos.","En su carta encontraremos tablas de embutidos, variedad de entrantes y picoteo para empezar y por último divide sus comidas en 'Del mar' y 'Del campo'.","En la Tasca el Aljibe encontraremos una gran variedad de vinos, canarios, nacionales y hasta portugueses. Tintos, blancos y espumosos."],
    ["Casa Pepe","Restaurante Casa Pepe",4,"","Paseo Werner Rautemberg, 5",38250,"922 54 09 58","","",28.55485,-16.34534,"Casa Pepe es uno de esos sitios que sorprenden, donde las materias primas de primerísima calidad son tratadas de manera genial. Son excepción los restaurante que a precios asequibles consiguen ofrecer un disfrute gastronómico de calidad. Casa Pepe es uno de ellos. Si tu camino te trae a Bajamar, no puedes dejar de visitarlo."," La comida de excelente calidad, pescado del día, todo recién hecho - mejor dejarse aconsejar según el apetito y el plan (compartir o no).","El trato es inmejorable y la comida de primera, teniendo en cuenta calidad-precio no hay nada comparable por los alrededores."],
    ["Pecatti Di Gola","Pecatti Di Gola",4,"","Calle Marques de Celada, 11",38202,"922 26 52 57","","https://www.facebook.com/pages/Peccati-DI-GOLA-La-Laguna/1506995572852125",28.49028,-16.321551,"Carta variada y con personalidad. Platos elaborados con mucho gusto y estilo. Ambiente muy agradable y servicio espectacular. Postres exquisitos y gran variedad de vinos. Un lugar muy recomendable que te invita a repetir.","Comida italiana autentica y creativa, fuera del tópicos de las pastas y las pizzas de muchos restaurantes italianos.","El restaurante Peccati di Gola tiene 2 ambientes agradables, no recargados, y no ruidosos, donde puedes mantener conversaciones disfrutando de la comida. Lo mejor, por supuesto, es la comida."],
    ["Casa de mi Abuela","Restaurante La Casa de Mi Abuela",4,"","Carretera del Monte de Las Mercedes, 6, Las Canteras",38293,"922 26 91 72","","https://www.facebook.com/RestauranteCasaDeMiAbuela",28.513519,-16.305637,"Restaurante de comida casera ubicado en Las Canteras en La Laguna. Ofrecemos auténtica comida canaria en La Laguna. Nuestras especialidades son el lomo de bacalao y las carnes a la parrilla.","Jamón serrano ibérico, Quesos canarios con confitura, Queso asado, Parrillada de verduras asadas, Gambas crujientes con albahaca, Milhojas de berenjena, bacalao y miel de palma, Croquetas caseras, Revuelto de gambas...","Se puede destacar el cuidado de los detalles en la presentación de sus platos, recetas tradicionales elaboradas con originalidad y con el sello propio del local, que hacen que algunos platos de siempre resulten más atractivos y novedosos."],
    ["100 Montaditos","100 Montaditos",4,"","Calle Obispo Rey Redondo, 16",38201,"902 19 74 94","","http://spain.100montaditos.com/",28.488256,-16.315854,"La historia comenzó en el año 2000 en una pequeña playa de Islantilla, Huelva, con un concepto revolucionario, sencillo, de operativa fácil, con ingredientes de alta calidad y con una gran variedad, además de una divertida manera de hacer los pedidos, una combinación que ha resultado ser un completo éxito.","La carta de 100 Montaditos es absolutamente genuina. Mezcla sencillez, variedad y calidad en una fórmula de éxito que ya forma parte del imaginario de la gente, todo el mundo sabe qué se come en 100 Montaditos. Una de las claves del éxito de la carta es el pan, un pan único.","Las 100 variedades de ingredientes son, sin duda, otro de los secretos del éxito de la marca. Hay un montadito para cada cliente y para todos los gustos y el gran número de opciones hace que el ritual de elegir tu pedido se haya convertido ya en un clásico entre los consumidores."],
    ["AJ Project","AJ Project Skateshop",5,"","Calle Herradores, 3",38204,"922 26 03 07","ajprojectjose@gmail.com","http://ajprojectskateshop.blogspot.com.es/",28.485939,-16.314646,"Tienda de zapatillas, skates y todo tipo de complementos y vestimenta relacionada con el mundo de los skaters. AJ Project y sus productos son bien conocidos por la mayoría de gente adolescente, son este tipo de personas las que suelen usar más sus prendas de vestir y sobretodo sus productos para patinar.","Comercializa marcas como Nike, Adidas, Hurley, Volcom, Diamond y demás...","También encontrarás aquí todo lo necesario para patinar con tu skate o comprarte uno aquí mismo."],
    ["Musicanarias","Musicanarias",5,"","Avenida El Paso, 29 ",38108,"922 82 16 64","eugenio@musicanarias.com","http://www.musicanarias.com/",28.458210,-16.301500,"En Musicanarias, con más de 50 años de experiencia, comercializamos las mejores marcas del mercado y ofrecemos soluciones objetivas y de calidad a nuestros clientes. La empresa cuenta con 2 divisiones, una de instrumentos musicales,...","El núcleo central de Musicanarias se encuentra ubicado en el no 29 de la avenida El Paso de Los Majuelos ( La Laguna ). Con más de 1000 m2 de infraestructura, la central de los Majuelos divide sus instalaciones en 3 grandes secciones: el almacén general, la administración y las exposiciones.","Hay hasta cuatro zonas de exposición diferentes: el hall donde se alberga una exposición general, la sala clásica, la sala de audiovisuales y la sala de instrumentos de viento."],
    ["Tecnisur Padel","Tecnisur Padel",6,"","Calle Punta Gorda, s/n",38108,"922 03 21 65","contacto@tecnisurpadel.es","https://tecnisur.padelclick.com/booking",28.459104,-16.298669,"Cuenta con 2.400 m² de superficie destinados a 6 pistas de pádel indoor reglamentarias, pistas verdes, pistas de competición con gradas, amplio espacio de desplazamiento interior, cafetería, zona de descanso y tienda. Además, presta servicios deportivos de entrenamiento de alto rendimiento y quiromasajista, escuela de pádel para todas las edades y niveles y organización de torneos amateur, empresas y federados.","Disfruta de un bono de 5, 10 o 20 clases de pádel. Las clases se imparten una o dos veces a la semana, en función de los grupos formados y se disfrutarán de forma continuada para aprovechar el curso al máximo.","¿Sabías que con el pádel se pueden llegar a quemar hasta 380 calorías por hora de juego, aportando fondo físico, agilidad y ayudando a cuidar nuestro sistema cardiovascular?."],
    ["El Muro","Rocódromo El Muro",6,"","Avenida Los Menceyes, 133",38205,"922 31 57 74","rocodromoelmuro@gmail.com","http://www.rocodromoelmuro.com/",28.475019,-16.305985,"El Muro nace de una ilusión, la de tener un lugar en el que poder practicar entre amigos un deporte que nos apasiona, en el que, independientemente a la climatología, poder hacerlo en casi cualquier momento del día. Fomentar este bonito deporte, tanto entre los más jóvenes como los más mayores y sin distinción alguna de genero o condición.","Construimos rocódromos bajo demanda, con experiencia de más de 10 años, en el sector de los comunmente llamados  'Trabajos Verticales' nos han dotado de la suficiente experiencia como para poder ofertar la fabircación de rocodromos bajo demanda.","Dentro de nuestras nuevas instalaciones iremos ofreciendo diferentes actividades y cursos que cubrirán todas las necesidades de nuestros clientes, pudiendo elegir el que mejor se adapte a tus necesidades. Nuestros colaboradores serán los encargados de impartir estos cursos y actividades."],
    ["Ciencia y el Cosmos","Museo de la Ciencia y el Cosmos",7,"","Avenida Los Menceyes, 70",38003,"922 20 93 20","","http://www.museosdetenerife.org/mcc-museo-de-la-ciencia-y-el-cosmose",28.475643,-16.30888,"El Museo de la Ciencia y el Cosmos no es un museo tradicional. Pertenece a una generación de museos de ciencia cuyo objetivo ya no es simplemente mostrar realizaciones científicas y técnicas de una época o de un lugar. El objetivo de estos museos es comunicar la ciencia, valiéndose para ello de todos los medios disponibles, especialmente la interactividad y la experimentación.","Pertenece al Organismo Autónomo de Museos y Centros del Cabildo de Tenerife. Fue inaugurado en 1993 por iniciativa del propio Cabildo y del Instituto de Astrofísica de Canarias.","Es ante todo un museo participativo, en el que el visitante tiene la oportunidad de experimentar por sí mismo las leyes y principios que rigen la Naturaleza."],
    ["Punto Zero","Bowling Punto Zero",7,"","Camino de la Hornera s/n",38291,"610 50 58 55","adolfobolera@hotmail.com","https://www.facebook.com/BowlingPuntoZero",28.463803,-16.305529,"Bolera Punto Zero ubicada en la parte baja del Centro Comercial Alcampo. Se alquilan pistas para uso privado, se organizan fiestas, etc. Todo ello al mejor precio y diversión.","Celebramos cumpleaños, cualquier tipo de eventos... hacemos la fiesta del pin de color casi todos los dias de la semana. Ven y diviertete.","Disponemos de globoflexía, pinta caras de diferentes personajes de dibujos animados."],
    ["Hotel Aguere","Hotel Aguere",7,"","Calle Obispo Rey Redondo, 55",38201,"922 31 40 36","reservas@hotelaguere.es","http://www.hotelaguere.es/",28.488514,-16.314826,"El Hotel Aguere, declarado Patrimonio Histórico-Artístico, está ubicado en pleno casco antiguo de la La Laguna (Tenerife), ciudad declarada Patrimonio de la Humanidad por la UNESCO. En nuestras 23 habitaciones ofrecemos a nuestros clientes un trato personalizado y el mejor servicio. Nos encontramos estratégicamente situados a tan sólo 10 minutos del aeropuerto Tenerife Norte (TFN), a menos de 15km de la capital Santa Cruz de Tenerife y muy próximo a zonas de senderismo, piscinas naturales y de campos de golf y equitación.","Completamente remodelado y situado en la antigua casa de los maqueses de Torrehermosa, edificio declarado Patrimonio Histórico-Artístico que está ubicado en pleno casco antiguo.","El edificio fue construído en 1760 por D. Cesáreo de la Torre y Ceballos, natural de Lima, capitán de Güímar y miembro de la Real Sociedad Económica de La Laguna, posteriomente pasó a ser Residencia del Obispo de Tenerife D. Luis Folgueras y también Colegio Mayor del Instituto de Canarias."],
    ["Simpalabras","Chupitería Simpalabras",8,"","Plaza Víctor Zurita Soler",38204,"656 824 173","","www.facebook.com/pages/Chupiteria-Simpalabras/1500240393539360?",28.483013,-16.314904,"Chupitería en el cuadrilátero de La Laguna ideal para tomar unos chupitos una noche de fiesta, con buen ambiente y mejor trato. La música varía según los días de la semana, teniendo cada día su estilo musical dentro de este pequeño pero conocido local.","Sin duda uno de los puntos fuertes de este local, con la mayoría de chupitos a 50 céntimos, esto aporta al éxito de la chupitería.","En la carta podemos encontrar una gran cantidad de chupitos diferentes y de todos los gustos y colores, literalmente."],
    ["Barock","Barock Tenerife",8,"","Avenida de Trinidad, 21",38204,"922 21 65 48","","http://www.barocktenerife.com/Barock/index.html",28.485989,-16.316248,"Música house en Barock, discoteca en San Cristóbal de la Laguna con capacidad para cerca de 1000 personas con casi 20 años de trayectoria. Todo un emblema en Tenerife las noches de jueves, viernes y sábados. Aquí se han dado cita actuaciones de artistas nacionales e internacionales, entre los que se cuentan David Guetta, Deep Dish, Steve Angello, Axwell, Tim Baker, X-Prees 2, The Scumfrog o Wally Lopez.","Pasa una noche en grande","Música, música y más música"]
]


sitios.each do |sit|
    s = Site.new(
        name: sit[0],       #string
        longname: sit[1],   #string
        category: sit[2],   #integer
        tags: sit[3],       #string
        address: sit[4],    #string
        postal: sit[5],     #integer
        phone: sit[6],      #string
        mail: sit[7],       #string
        webpage: sit[8],    #string
        latitude: sit[9],   #float x.123456
        longitude: sit[10],  #float
        text1: sit[11],     #text
        text2: sit[12],     #text
        text3: sit[13]      #text
    )
    s.save!
end
